import { badRequest } from './errors'
import { isUlid } from './ids'

/**
 * Small hand-written validators instead of a schema library.
 *
 * Zod would be nicer to read, but it is ~14kB into a Worker bundle that is
 * otherwise dependency-free, and it runs on every cold start. There are nine
 * request bodies in this API; this covers them and adds nothing to the bundle.
 *
 * Every failure is a 400 carrying the field name, so the client can point at
 * the input that was wrong rather than showing a generic error.
 */

export class Validator {
  private errors: Record<string, string> = {}

  constructor(private body: Record<string, unknown>) {}

  private fail(field: string, message: string) {
    /* Keep the first failure per field — the later ones are usually
       consequences of the first and only add noise to the response. */
    if (!this.errors[field]) this.errors[field] = message
  }

  /** Trimmed, length-checked string. Returns '' when invalid; check `finish()`. */
  string(
    field: string,
    { min = 0, max = Infinity, required = true, trim = true }: StringOptions = {}
  ): string {
    const raw = this.body[field]

    if (raw === undefined || raw === null) {
      if (required) this.fail(field, `${label(field)} is required`)
      return ''
    }
    if (typeof raw !== 'string') {
      this.fail(field, `${label(field)} must be text`)
      return ''
    }

    const value = trim ? raw.trim() : raw
    if (value.length < min) {
      this.fail(
        field,
        min === 1
          ? `${label(field)} is required`
          : `${label(field)} must be at least ${min} characters`
      )
    }
    if (value.length > max) {
      this.fail(field, `${label(field)} must be ${max} characters or fewer`)
    }
    return value
  }

  /**
   * Passwords are length-checked but never trimmed: a leading or trailing
   * space is a legitimate character, and silently stripping it would make a
   * correct password fail to match its own hash.
   */
  password(field: string, { min = 8, max = 200 }: { min?: number; max?: number } = {}): string {
    const raw = this.body[field]
    if (typeof raw !== 'string' || raw.length === 0) {
      this.fail(field, 'Password is required')
      return ''
    }
    if (raw.length < min) this.fail(field, `Password must be at least ${min} characters`)
    if (raw.length > max) this.fail(field, `Password must be ${max} characters or fewer`)
    return raw
  }

  email(field: string): string {
    const value = this.string(field, { min: 3, max: 254 })
    if (value && !EMAIL_RE.test(value)) this.fail(field, 'Enter a valid email address')
    return value.toLowerCase()
  }

  /** An id generated by this API. Rejects anything that is not a ULID. */
  id(field: string, { required = true }: { required?: boolean } = {}): string {
    const raw = this.body[field]
    if (raw === undefined || raw === null) {
      if (required) this.fail(field, `${label(field)} is required`)
      return ''
    }
    if (typeof raw !== 'string' || !isUlid(raw)) {
      this.fail(field, `${label(field)} is not a valid id`)
      return ''
    }
    return raw
  }

  /**
   * A client-generated idempotency key. Not a ULID — it comes from
   * `crypto.randomUUID()` in the browser — so it is only bounded and
   * character-checked, never trusted for ordering.
   */
  clientId(field: string): string | null {
    const raw = this.body[field]
    if (raw === undefined || raw === null || raw === '') return null
    if (typeof raw !== 'string' || raw.length > 64 || !/^[A-Za-z0-9._:-]+$/.test(raw)) {
      this.fail(field, 'Invalid client id')
      return null
    }
    return raw
  }

  optionalString(field: string, max: number): string | undefined {
    if (this.body[field] === undefined) return undefined
    return this.string(field, { max, required: false })
  }

  /** Throws if anything failed. Call once, at the end of every handler. */
  finish(): void {
    const fields = Object.keys(this.errors)
    if (fields.length === 0) return
    throw badRequest(this.errors[fields[0]], { fields: this.errors })
  }
}

interface StringOptions {
  min?: number
  max?: number
  required?: boolean
  trim?: boolean
}

/* Deliberately permissive. Strict RFC 5322 rejects addresses that work, and
   the only authoritative check is sending mail to it.
   TODO: verification email once a mail provider is chosen. */
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/

const LABELS: Record<string, string> = {
  displayName: 'Name',
  peerId: 'Recipient',
  lastReadMessageId: 'Message',
  replyToId: 'Reply target',
  refreshToken: 'Refresh token',
}

function label(field: string): string {
  return LABELS[field] ?? field.charAt(0).toUpperCase() + field.slice(1)
}

export function validate(body: Record<string, unknown>): Validator {
  return new Validator(body)
}

/** Query-string equivalents, which have no body to validate. */
export function queryInt(
  url: URL,
  key: string,
  { fallback, max, min = 1 }: { fallback: number; max: number; min?: number }
): number {
  const raw = url.searchParams.get(key)
  if (raw === null) return fallback
  const parsed = Number(raw)
  if (!Number.isFinite(parsed)) return fallback
  return Math.min(max, Math.max(min, Math.floor(parsed)))
}
